project_id = "panvkamncrfazyrqdcpm"

[functions.request-password-otp]
verify_jwt = false

[functions.verify-password-otp]
verify_jwt = false

[functions.request-email-otp]
verify_jwt = false

[functions.verify-email-otp]
verify_jwt = false

[functions.create-admin]
verify_jwt = true

[functions.list-admins]
verify_jwt = true

[functions.update-admin]
verify_jwt = true

[functions.delete-admin]
verify_jwt = true
