const workers = [
 {id:1,name:'Ravi Kumar',skill:'Electrician',rating:4.9,reviews:126,price:450,exp:'8 years exp.',available:'Available today',avatar:'RK'},
 {id:2,name:'Suresh Patel',skill:'Plumber',rating:4.8,reviews:98,price:400,exp:'6 years exp.',available:'Available today',avatar:'SP',tone:'orange'},
 {id:3,name:'Mohammed Ali',skill:'Carpenter',rating:4.9,reviews:76,price:500,exp:'10 years exp.',available:'Available tomorrow',avatar:'MA',tone:'green'},
 {id:4,name:'Anil Verma',skill:'Painter',rating:4.7,reviews:64,price:380,exp:'7 years exp.',available:'Available today',avatar:'AV',tone:'orange'},
 {id:5,name:'Deepak Singh',skill:'Electrician',rating:4.6,reviews:49,price:420,exp:'5 years exp.',available:'Available this week',avatar:'DS',tone:'green'},
 {id:6,name:'Kiran Das',skill:'Plumber',rating:4.8,reviews:82,price:430,exp:'9 years exp.',available:'Available tomorrow',avatar:'KD'}
];
let bookings = [
 {id:10,name:'Ravi Kumar',skill:'Electrician',date:'Today, 2:00 PM',day:'05',month:'AUG',status:'confirmed',tab:'active',avatar:'RK',tone:''},
 {id:11,name:'Suresh Patel',skill:'Plumber',date:'Tomorrow, 10:00 AM',day:'06',month:'AUG',status:'pending',tab:'active',avatar:'SP',tone:'orange'},
 {id:12,name:'Mohammed Ali',skill:'Carpenter',date:'08 Aug, 9:00 AM',day:'08',month:'AUG',status:'confirmed',tab:'upcoming',avatar:'MA',tone:'green'}
];
const $ = s => document.querySelector(s), $$ = s => [...document.querySelectorAll(s)];
function nav(page){$$('.page').forEach(p=>p.classList.toggle('active',p.id===page));$$('.nav-link').forEach(a=>a.classList.toggle('active',a.dataset.page===page));location.hash=page;$('#sidebar').classList.remove('open');$('#overlay').classList.remove('show');window.scrollTo(0,0)}
function avatar(w){return `<div class="labour-avatar ${w.tone||''}">${w.avatar}</div>`}
function renderWorkers(){let term=$('#searchInput').value.toLowerCase(), cats=$$('.category-filter:checked').map(x=>x.value), availability=$('input[name=availability]:checked')?.value, min=+$('input[name=rating]:checked')?.value||0;let list=workers.filter(w=>(w.name+' '+w.skill).toLowerCase().includes(term)&&(!cats.length||cats.includes(w.skill))&&(!min||w.rating>=min)&&(!availability||(availability==='today'?w.available==='Available today':w.available!=='Available today')));let sort=$('#sortSelect').value;if(sort==='rating')list.sort((a,b)=>b.rating-a.rating);if(sort==='price')list.sort((a,b)=>a.price-b.price);$('#resultCount').textContent=list.length;$('#labourGrid').innerHTML=list.length?list.map(w=>`<article class="labour-card"><div class="labour-head">${avatar(w)}<div><h3>${w.name}</h3><span class="skill">${w.skill} · ${w.exp}</span></div></div><div class="rating">★ ${w.rating}<span>(${w.reviews} reviews)</span></div><div class="card-meta"><span>${w.available}</span><b>₹${w.price}/visit</b></div><button class="book-btn" data-book="${w.id}">Book now</button></article>`).join(''):`<p class="subtext">No professionals match your filters. Try clearing a filter.</p>`;updateFilterCount()}
function updateFilterCount(){let n=$$('input[type=checkbox]:checked,input[type=radio]:checked').length;$('#filterCount').textContent=n;$('#filterCount').style.display=n?'inline':'none'}
function renderDashboard(){let b=bookings.find(x=>x.tab==='active');$('#dashboardBookings').innerHTML=b?`<div class="mini-booking"><div class="mini-date"><b>${b.day}</b><small>${b.month}</small></div>${avatar(b)}<div><strong>${b.name}</strong><p>${b.skill} · ${b.date}</p></div><span class="status ${b.status}">${b.status==='confirmed'?'Confirmed':'Pending'}</span></div>`:'<p class="subtext">No active booking — find a professional when you need one.</p>'}
function renderBookings(tab='active'){let list=bookings.filter(b=>b.tab===tab);$('#bookingList').innerHTML=list.length?list.map(b=>`<article class="booking-card">${avatar(b)}<div class="booking-info"><h3>${b.name} <span class="status ${b.status}">${b.status==='confirmed'?'Confirmed':'Pending'}</span></h3><p>${b.skill}</p><p class="job-date">◷ ${b.date}</p></div><div class="card-actions">${tab==='active'?`<button class="secondary-btn" data-go="find-labour">Message</button><button class="cancel-btn" data-cancel="${b.id}">Cancel</button>`:`<button class="secondary-btn" data-rebook="${b.name}">Book again</button>`}</div></article>`).join(''):`<div class="mini-booking"><p class="subtext">Nothing here yet.</p></div>`;$('#activeCount').textContent=bookings.filter(b=>b.tab==='active').length;$('#upcomingCount').textContent=bookings.filter(b=>b.tab==='upcoming').length;$('#bookingBadge').textContent=bookings.filter(b=>b.tab==='active').length}
function showToast(message){let t=$('#toast');t.textContent=message;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2800)}
let selectedWorker;
function openBook(id){selectedWorker=workers.find(w=>w.id===+id)||workers[0];$('#bookName').textContent=selectedWorker.name;$('#bookMeta').textContent=`${selectedWorker.skill} · ₹${selectedWorker.price}/visit · ${selectedWorker.rating} ★`;let d=new Date();d.setDate(d.getDate()+1);$('#bookingDate').min=d.toISOString().slice(0,10);$('#bookingDate').value=d.toISOString().slice(0,10);$('#bookingDialog').showModal()}
function renderNotices(){const notices=[['Booking confirmed','Ravi Kumar has confirmed your booking for today at 2:00 PM.','10 min ago','✓'],['A professional replied','Suresh Patel is reviewing your plumbing request.','1 hour ago','⌁'],['Payment reminder','Your invoice for the completed painting job is ready.','Yesterday','₹']];$('#notificationList').innerHTML=notices.map((n,i)=>`<article class="notice ${i<2?'unread':''}"><div class="notice-icon">${n[3]}</div><div><h3>${n[0]}</h3><p>${n[1]}</p></div><time>${n[2]}</time></article>`).join('')}
document.addEventListener('click',e=>{let go=e.target.closest('[data-go]');if(go)nav(go.dataset.go);let book=e.target.closest('[data-book]');if(book)openBook(book.dataset.book);let cancel=e.target.closest('[data-cancel]');if(cancel){bookings=bookings.filter(b=>b.id!==+cancel.dataset.cancel);renderBookings('active');renderDashboard();showToast('Booking cancelled successfully.')}let reb=e.target.closest('[data-rebook]');if(reb){let w=workers.find(x=>x.name===reb.dataset.rebook)||workers[0];openBook(w.id)}});
$$('.nav-link').forEach(a=>a.addEventListener('click',()=>nav(a.dataset.page)));$('#menuBtn').onclick=()=>{$('#sidebar').classList.add('open');$('#overlay').classList.add('show')};$('#overlay').onclick=()=>{$('#sidebar').classList.remove('open');$('#overlay').classList.remove('show')};$('#filterToggle').onclick=()=>$('#filterPanel').classList.toggle('open');$('#searchInput').oninput=renderWorkers;$('#sortSelect').onchange=renderWorkers;$$('.filter-panel input').forEach(x=>x.onchange=renderWorkers);$('#clearFilters').onclick=()=>{$$('.filter-panel input').forEach(x=>x.checked=false);renderWorkers()};$$('.booking-tabs button').forEach(x=>x.onclick=()=>{$$('.booking-tabs button').forEach(b=>b.classList.remove('active'));x.classList.add('active');renderBookings(x.dataset.tab)});$('#rebookBtn').onclick=()=>openBook(1);$('#notificationBtn').onclick=()=>nav('notifications');$('#markRead').onclick=()=>{$$('.notice').forEach(n=>n.classList.remove('unread'));$('#noticeBadge').style.display='none';showToast('All notifications marked as read.')};$('#helpBtn').onclick=()=>showToast('Support is available at help@skilliant.in');$$('.close-dialog').forEach(x=>x.onclick=()=>x.closest('dialog').close());$('#bookingForm').onsubmit=e=>{e.preventDefault();let date=new Date($('#bookingDate').value+'T12:00:00');bookings.unshift({id:Date.now(),name:selectedWorker.name,skill:selectedWorker.skill,date:date.toLocaleDateString('en-IN',{day:'numeric',month:'short'})+', '+$('#bookingTime').value,day:String(date.getDate()).padStart(2,'0'),month:date.toLocaleDateString('en-IN',{month:'short'}).toUpperCase(),status:'pending',tab:'active',avatar:selectedWorker.avatar,tone:selectedWorker.tone});$('#bookingDialog').close();$('#confirmedName').textContent=selectedWorker.name;$('#confirmationDialog').showModal();renderBookings('active');renderDashboard()};$$('.close-confirm').forEach(x=>x.onclick=()=>{$('#confirmationDialog').close();if(x.textContent.includes('View'))nav('bookings')});renderWorkers();renderDashboard();renderBookings();renderNotices();
